FROM ghcr.io/linuxserver/baseimage-rdesktop-web:arm32v7-focal

# set version label
ARG BUILD_DATE
ARG VERSION
ARG CALIBRE_RELEASE
LABEL build_version="Linuxserver.io version:- ${VERSION} Build-date:- ${BUILD_DATE}"
LABEL maintainer="aptalca"

# add local files
COPY root-armhf/ /

# This Calibre image does not support 32 bit ARM due to lack of upstream support