#!/usr/bin/with-contenv bash
# shellcheck shell=bash

# make our folders
mkdir -p /config/.config/calibre

# set webserver port on first install
if [[ ! -f /config/.config/calibre/server-config.txt ]]; then
    echo "port 8081" > /config/.config/calibre/server-config.txt
fi

# default file copies first run
if [[ ! -f /config/.config/openbox/menu.xml ]]; then
    mkdir -p /config/.config/openbox && \
    cp /defaults/menu.xml /config/.config/openbox/menu.xml && \
    lsiown -R abc:abc /config/.config
fi

# permissions
lsiown -R abc:abc \
    /config
