#!/usr/bin/with-contenv bash
# shellcheck shell=bash

# make our folders
mkdir -p /config/.config/calibre

# set webserver port on first install
if [[ ! -f /config/.config/calibre/server-config.txt ]]; then
    echo "port 8081" > /config/.config/calibre/server-config.txt
fi

if [[ ! -f /config/.config/calibre/tweaks.json ]]; then
    rsync -av -f'- dep*/' -f'- run' -f'- type' -f'- up' /etc/s6-overlay/s6-rc.d/init-calibre-config/ /config/.config/calibre/
fi

if [[ -d /config/ssl ]]; then
    sed -i '/ssl/s/^/# /' /etc/nginx/sites-*/*
    rm -rf /config/ssl
fi

# default file copies first run
if [[ ! -f /config/.config/openbox/menu.xml ]]; then
    mkdir -p /config/.config/openbox && \
    cp /defaults/menu.xml /config/.config/openbox/menu.xml && \
    lsiown -R abc:abc /config/.config
fi

# permissions
lsiown -R abc:abc \
    /config
