#!/usr/bin/with-contenv bash
# shellcheck shell=bash

cat <<-EOF
    ********************************************************
    ********************************************************
    *                                                      *
    *                         !!!!                         *
    *         This Calibre image does not support          *
    *        ARM due to a lack of upstream packages        *
    *                                                      *
    *                                                      *
    ********************************************************
    ********************************************************
EOF
