#!/usr/bin/with-contenv bash

# make our folders
mkdir -p /config/.config/calibre

# set webserver port on first install
[[ ! -f /config/.config/calibre/server-config.txt ]] && \
    echo "port 8081" > /config/.config/calibre/server-config.txt

sed -i 's|"password":"abc",|"password":"kjhbouygiuvhgvghv",|' /gclient/app.js
sed -i "s#process.env.PASSWORD || 'abc';#process.env.PASSWORD || 'kjhbouygiuvhgvghv';#" /gclient/maketoken.js
if ([ -n "$GUAC_USER" ] || [ -n "$GUAC_PASS" ]) && [ -z "$PASSWORD" ]; then
    echo '
********************************************************
********************************************************
****                                                ****
****  GUAC_USER and GUAC_PASS vars are deprecated   ****
****                                                ****
****  Temporary credentials are being set:          ****
****                                                ****
****  User: abc                                     ****
****  Pass: abc                                     ****
****                                                ****
****                                                ****
****  See the readme for new credential info        ****
****                                                ****
****                                                ****
********************************************************
********************************************************'
elif [ -n "$PASSWORD" ]; then
    echo "abc:${PASSWORD}" | chpasswd
    echo "Setting password from environment variable."
else 
    echo "abc:kjhbouygiuvhgvghv" | chpasswd
    echo "No password is set for the interface."
fi

# default file copies first run
[[ ! -f /config/.config/openbox/menu.xml ]] && \
    mkdir -p /config/.config/openbox && \
    cp /defaults/menu.xml /config/.config/openbox/menu.xml && \
    chown -R abc:abc /config/.config

# permissions
chown -R abc:abc \
    /config \
    /opt/calibre
