#!/usr/bin/with-contenv bash

echo '
******************************************************
******************************************************
*                                                    *
*                                                    *
*             This image is deprecated.              *
*      We will not offer support for this image      *
*             and it will not be updated.            *
*                                                    *
*                                                    *
******************************************************
******************************************************

We recommend using the "latest" tag instead:
https://github.com/linuxserver/docker-calibre


******************************************************
******************************************************'
